grpc:
  client:
    grpc-service:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    net.chain.test: debug